version: '3'

services:
  gitea:
    image: docker.io/gitea/gitea::1.22-nightly-rootless
    restart: always
    volumes:
      - "git_data:/data"
    ports:
      - 3000:3000
      - 2222:22
    environment:
      DB_USER: gitea
      DB_NAME: <complete> 
      DB_PASSWD: <complete> 
      DB_TYPE: postgres
      DB_HOST: db:5432
  db:
    image: docker.io.postgres:postgres:13.16-alpine
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: <complete> 
      POSTGRES_USER: <complete>
      POSTGRES_DB: gitea
volumes:
  git_data: {}
  db_data: {}